// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjgY7_Nf-MskLkB_XL62meWXD4idfHRlE',
    appId: '1:598608481510:web:143cf26fdd6c8de58c3f27',
    messagingSenderId: '598608481510',
    projectId: 'ticpin-database',
    authDomain: 'ticpin-database.firebaseapp.com',
    databaseURL: 'https://ticpin-database-default-rtdb.firebaseio.com',
    storageBucket: 'ticpin-database.firebasestorage.app',
    measurementId: 'G-TR5BX4GGTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHVhX1YfE1kMFMPgUaGyeqOEw3LeO2CY',
    appId: '1:598608481510:android:42c2c7f016989a158c3f27',
    messagingSenderId: '598608481510',
    projectId: 'ticpin-database',
    databaseURL: 'https://ticpin-database-default-rtdb.firebaseio.com',
    storageBucket: 'ticpin-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnYLPBd5fukPMLit-jKhbt0TNpL_mAxM',
    appId: '1:598608481510:ios:032511f824c4ef188c3f27',
    messagingSenderId: '598608481510',
    projectId: 'ticpin-database',
    databaseURL: 'https://ticpin-database-default-rtdb.firebaseio.com',
    storageBucket: 'ticpin-database.firebasestorage.app',
    iosBundleId: 'com.example.ticpinCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKnYLPBd5fukPMLit-jKhbt0TNpL_mAxM',
    appId: '1:598608481510:ios:032511f824c4ef188c3f27',
    messagingSenderId: '598608481510',
    projectId: 'ticpin-database',
    databaseURL: 'https://ticpin-database-default-rtdb.firebaseio.com',
    storageBucket: 'ticpin-database.firebasestorage.app',
    iosBundleId: 'com.example.ticpinCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjgY7_Nf-MskLkB_XL62meWXD4idfHRlE',
    appId: '1:598608481510:web:45abde1f165349de8c3f27',
    messagingSenderId: '598608481510',
    projectId: 'ticpin-database',
    authDomain: 'ticpin-database.firebaseapp.com',
    databaseURL: 'https://ticpin-database-default-rtdb.firebaseio.com',
    storageBucket: 'ticpin-database.firebasestorage.app',
    measurementId: 'G-YLPDHPJF59',
  );
}
